Jatpack compose
DimaMaligon/EnglishWords pull request #1
Opened 2023-04-10 17:51 UTC by DimaMaligon

I transfered app project to jatpack compose. Add backArrow button to ActionStatusBar, but it isn't work yet. Also I did that you can scroll the list of words if you tap on list and move down or up.

2023-04-10 18:08 UTC, IvanShalimov commented
Надо отредактировать, добавить .gitignore

2023-04-11 13:48 UTC, DimaMaligon commented
> Надо отредактировать, добавить .gitignore Посмотри тут: https://github.com/receipt-project/receipt-android/blob/master/.gitignore
Я отредактировал. А ты остальное смотрел?

2023-04-12 10:04 UTC, IvanShalimov requested changes
Needs work

2023-04-12 10:04 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/LetterActivity.kt
> +import androidx.compose.ui.unit.dp
Посмотри неиспользуемые импорты.

2023-04-12 10:04 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/LetterAll.kt
> +
Лишний пробел

2023-04-12 10:04 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/LetterAll.kt
> +    val letters = remember {
Не должно ли это быть выше? В другом файле или не переменной функции, а файла?

2023-04-12 10:04 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/LetterAll.kt
> +                  index ->
Лишний перенос

2023-04-12 10:04 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/LetterListItem.kt
> +                text = letter.toString(),
toString не нужен

2023-04-12 10:04 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/MainActivity.kt
> +                startActivity(ProfileActivity.newIntent(this, it))
Почему тут ProfileActivity, а не LetterActivity?

2023-04-12 10:04 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/MainActivity.kt
> +fun MyApp(navigationToProfile: (String) -> Unit) {
Возможно нужно сделать превью (Compose @Preview)

2023-04-12 10:04 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/LetterActivity.kt
> -class LetterActivity : AppCompatActivity() {
![image](https://user-images.githubusercontent.com/16368990/230972987-1d6db6d1-8814-4811-8ee2-26b3b1a878d6.png)

2023-04-12 10:04 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/LetterActivity.kt
> +        Button(onClick = {
При клике список сверху не перерисуется

2023-04-12 10:04 UTC, IvanShalimov commented on app/src/main/AndroidManifest.xml
> +        <activity
Что это такое?

2023-04-12 12:14 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/LetterAll.kt
> +    val letters = remember {
https://startandroid.ru/ru/courses/compose/30-course/compose/672-urok-9-remember.html А зачем в другом файле, мы только ту и используем. И именно тут, нам нужно использовать

2023-04-12 12:19 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/LetterAll.kt
> +                  index ->
![Uploading Снимок экрана 2023-04-12 151825.png…]()

2023-04-12 12:19 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/LetterAll.kt
> +                  index ->
у меня все норм

2023-04-12 12:20 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/LetterAll.kt
> +                  index ->
![Снимок экрана 2023-04-12 151825](https://user-images.githubusercontent.com/46076389/231455112-360757c5-8d34-472c-96f6-762786f86abb.png)

2023-04-12 15:19 UTC, DimaMaligon commented on app/src/main/AndroidManifest.xml
> +        <activity
поправил, была путаница с активитими

2023-04-12 15:20 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/LetterActivity.kt
> +        Button(onClick = {
сделал, что прорисовывается, но как-то через раз работает, пока не пойму, что делать((

2023-04-12 15:20 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/MainActivity.kt
> +fun MyApp(navigationToProfile: (String) -> Unit) {
сделал

2023-04-12 15:21 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/MainActivity.kt
> +                startActivity(ProfileActivity.newIntent(this, it))
поправил, не везде поменял на новое название

2023-04-12 15:21 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/LetterListItem.kt
> +                text = letter.toString(),
сделано

2023-04-12 15:22 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/LetterAll.kt
> +
поправил

2023-04-12 15:22 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/LetterActivity.kt
> +import androidx.compose.ui.unit.dp
сделал

2023-04-12 18:21 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/MainActivity.kt
> +                startActivity(ProfileActivity.newIntent(this, it))
Windows: Shift+F6 - Переименование переменной.

2023-04-12 19:39 UTC, merged