Перевод проекта на Room
DimaMaligon/EnglishWords pull request #35
Opened 2023-06-21 06:56 UTC by DimaMaligon

Я все-таки перевел проект на Room. Сейчас вместо кучи сущностей существует только энтити Word со всеми необходимыми параметрами. 

на смену Sqllite классам пришли:
WordDao - запросы для работы с бд
Word - сущность
DbManager - управление бд, создание ее
DataBaseWord - параметры бд

В результате переноса отвалились Упражнения. Создам баг на исправление этого безобразия. В остально все работает.

2023-06-21 19:10 UTC, IvanShalimov requested changes
Нужно доработать. Применить цикл во View

2023-06-21 19:10 UTC, IvanShalimov commented on app/build.gradle
> +    ext.kotlin_version = '1.9.0'
Это все необходимо для Room?

2023-06-21 19:10 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/room/DataBaseWord.kt
> +abstract class DataBaseWord : RoomDatabase() {
кайфуха

2023-06-21 19:10 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/room/WordDao.kt
> +    @Query("SELECT * FROM word ORDER BY RANDOM() LIMIT 4")
кайфуха

2023-06-21 19:10 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/screens/LetterScreen.kt
> +fun WordList(listWords: List<Word>) {
Круть

2023-06-21 19:10 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/screens/RepeatWordsScreen.kt
>                  onClick = {
Может это стоит обернуть в цикл?

2023-06-21 19:10 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/viewmodel/LetterViewModel.kt
> +//            if(word != null){
Почему оставил комментарий, нужно сохранить для чего-то?

2023-06-21 19:30 UTC, DimaMaligon commented on app/build.gradle
> +    ext.kotlin_version = '1.9.0'
да, давно не работал с этим приложение и многие версии устарели, решил обновить.

2023-06-21 19:32 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/screens/RepeatWordsScreen.kt
>                  onClick = {
можно попробовать

2023-06-21 19:32 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/viewmodel/LetterViewModel.kt
> +//            if(word != null){
надо удалить, тестил кое-что

2023-06-30 06:43 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/screens/RepeatWordsScreen.kt
>                  onClick = {
Есть идея обернуть в Lazy Grid  оберну в следующем пр

2023-06-30 06:45 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/viewmodel/LetterViewModel.kt
> +//            if(word != null){
delete comment

2023-06-30 06:45 UTC, merged