add clean architecture model
DimaMaligon/EnglishWords pull request #48
Opened 2023-08-04 06:59 UTC by DimaMaligon

Сделал предварительные настройки слоев clean architecture, но еще не внедрил в слой презентер и т.д Сейчас с помощью этого реквеста хочу понять, я иду по правильному пути или нет.

Что сделал:
**data слой** 
включает в себя: 
_model_ - моделька объекта с которым работаем.
_repositories_ - репозиторий для работы с источником данных
_sources_ - источники данных
_Mapper_ - интерфейс для создания шаблона перевода модельки domain to data и наоборот
_WordStorage_ - интерфейс для создания шаблона источника данных

**domain слой**
_model_ - моделька объекта с которым работаем.
_repositoriy_ - репозиторий источника данных
_usecases_ - пользовательские сценарии

2023-08-05 06:52 UTC, IvanShalimov approved these changes
Есть некоторые субъективные замечания связанные со стилем кода. 
Замечания по размещению логики.
С UseCase'ами в будущем скорей всего придется работу переделать. Почему потом, а не сейчас? Надо выявить как usecase группируются между собой, и на основе этого анализа объединить их в единые сценарии(принцип единой ответственности при этом не нарушится)

2023-08-05 06:52 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/data/repositories/EnglishWordRepositoryImpl.kt
> +class EnglishWordRepositoryImpl(val wordStorage: WordStorage, val mapper: Mapper) : EnglishWordRepository {
Пока у тебя один Mapper - это терпимое название. Но если их будет больше.... Постарайся давать более осмысленные названия.

2023-08-05 06:52 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/data/repositories/EnglishWordRepositoryImpl.kt
> +        val listWords = listWordsStorage.stream().map {
Популярный подход к стилю кода, где map переносят на следующую строку.

2023-08-05 06:52 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/domain/repository/EnglishWordRepository.kt
> + fun checkListIsEmpty(): Boolean
Всякие проверки как мне кажется не могут быть публичными методами репозитория. Скорее это для интерактора или вью-модель логика. Либо это должно быть что-то внутреннее для репозитория.

2023-08-05 06:52 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/domain/usecases/AddNewWordUseCase.kt
> +class AddNewWordUseCase(private val englishRoomRepository: EnglishWordRepository) {
👍

2023-08-05 06:52 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/domain/usecases/GetEnglishListLetterUseCase.kt
> +    suspend fun execute(letter:String): MutableList<Word> {
Это один из подходов. Если чесло UseCase'ов начнет расти неконтролируемо, подумай об объединение их в разные группы. Возможно даже за счет делегатов(совет на будущее)

2023-08-08 06:36 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/domain/repository/EnglishWordRepository.kt
> + fun checkListIsEmpty(): Boolean
Ну мне тоже так казалось. Но по сути у нас есть кейс, где нам нужно проверить, что есть определенное число слов и если это количество меньше, то выводить попап, если нет то все ок. Плюс мы проверяем количество слов, которое поступило, нам не важно, что за источник, а лишь количество.

2023-08-08 07:05 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/domain/usecases/GetEnglishListLetterUseCase.kt
> +    suspend fun execute(letter:String): MutableList<Word> {
Сделал вариант с вложенными классами. т.е Сделал класс соответствующий определенным кейсам и в него вложил классы.

2023-08-08 07:05 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/domain/repository/EnglishWordRepository.kt
> + fun checkListIsEmpty(): Boolean
Можешь прокомментировать мои мысли?

2023-08-08 07:05 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/data/repositories/EnglishWordRepositoryImpl.kt
> +        val listWords = listWordsStorage.stream().map {
done

2023-08-09 13:50 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/domain/repository/EnglishWordRepository.kt
> + fun checkListIsEmpty(): Boolean
Я не понял мысль. Прочитал 4 раза х)

2023-08-09 13:54 UTC, IvanShalimov requested changes
Нужно поправить опечатку. Ответить на вопрос. И уточнить свой вопрос

2023-08-09 13:54 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/domain/usecases/RepeatWordsUseCases.kt
> +        suspend fun дexecute(): MutableList<Word> {
Лишний символ в именовании "д"

2023-08-09 13:54 UTC, IvanShalimov commented on app/src/main/java/com/example/englishwords/domain/usecases/RepeatWordsUseCases.kt
> +    class CheckListWordsIsEmptyUseCase (private val englishRoomRepository: EnglishWordRepository) {
А еще остается смысл в отдельных классах?

2023-08-09 14:00 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/domain/repository/EnglishWordRepository.kt
> + fun checkListIsEmpty(): Boolean
облегчил свой словесный понос)) перечитай еще раз плиз)

2023-08-09 14:01 UTC, DimaMaligon commented on app/src/main/java/com/example/englishwords/domain/usecases/RepeatWordsUseCases.kt
> +    class CheckListWordsIsEmptyUseCase (private val englishRoomRepository: EnglishWordRepository) {
не очень понял

2023-09-15 08:10 UTC, merged